name: Validate bootc build and release

on:
  push:
    branches:
      - main

env:
  REGISTRY_USER: rh-ee-chbutler
  IMAGE_REGISTRY: quay.io
  IMAGE: bootc-kiosk

jobs:
  testbuild:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Quay.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: ${{ env.IMAGE_REGISTRY }}

    - name: Log in to registry.redhat.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: registry.redhat.io


    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: "${{ env.IMAGE }}"
        tags: latest ${{ github.sha }}
        containerfiles: |
         ./Containerfile
  release:
    runs-on: ubuntu-latest
    needs: testbuild
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
        token: ${{ secrets.FG_PAT }}
    - name: Python Semantic Release
      id: release
      uses: python-semantic-release/python-semantic-release@v9.8.8
      with:
        github_token: ${{ secrets.FG_PAT }}